---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-monitor
  namespace: utilities

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: node-monitor
  namespace: utilities
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: node-monitor
roleRef:
  kind: ClusterRole
  name: node-monitor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: node-monitor
  namespace: utilities